version: "3.1"

services:
  upstream:
    build: ./services/upstream
    ports:
      - 4000:4000
    volumes:
      - ./services/upstream:/usr/share/nginx/html:ro
    environment:
      PORT: 4000

  tailor:
    build: ./services/tailor
    ports:
      - 8080:8080
    environment:
      PORT: 8080
      UPSTREAM_URL: http://upstream:4000
