version: "3.1"

services:
  upstream:
    build: ./services/upstream
    ports:
      - 4000:4000
    environment:
      PORT: 4000
      COMPONENT_URL: http://localhost:3000
    networks:
      - tu

  tailor:
    build: ./services/tailor
    ports:
      - 8080:8080
    environment:
      PORT: 8080
      UPSTREAM_URL: https://host.docker.internal:9002
      NODE_TLS_REJECT_UNAUTHORIZED: 0
    networks:
      - tu

  component:
    build: ./services/component
    ports:
      - 3000:3000
    environment:
      PORT: 3000
    networks:
      - tu

networks:
  tu:
    external:
      name: tu