version: "3.1"

services:
  upstream:
    build: ./services/upstream
    ports:
      - 4000:4000
    environment:
      PORT: 4000
      COMPONENT_URL: http://localhost:3000
    networks:
      - tu

  tailor:
    build: ./services/tailor
    ports:
      - 8080:8080
    environment:
      PORT: 8080
      UPSTREAM_URL: https://host.docker.internal:9002
      NODE_TLS_REJECT_UNAUTHORIZED: 0
    networks:
      - tu

  header:
    build: services/header
    ports:
      - 3010:3010
    environment:
      PORT: 3010
    networks:
      - tu

  sort:
    build: services/sortWithoutOC
    ports:
      - 3020:3020
    environment:
      PORT: 3020
    networks:
      - tu

  stitcher:
    build: ./services/stitcher
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      UPSTREAM_URL: https://host.docker.internal
      HYBRIS_PORT: 9002
      HEADER_PORT: 3010
      SORT_PORT: 3020
      NODE_TLS_REJECT_UNAUTHORIZED: 0
    networks:
      - tu

networks:
  tu:
    external:
      name: tu