version: '3.1'

services:
  nova-cluster:
    build: ./services/nova-cluster
    ports:
      - 3000:3000
    environment:
      PORT: 3000

  nova-proxy:
    build: ./services/nova-proxy
    ports:
      - 8080:8080
    environment:
      PORT: 8080
      HYPERNOVA_BATCH: http://nova-cluster:3000/batch
      UPSTREAM: http://upstream:4000

  upstream:
    build: ./services/upstream
    ports:
      - 4000:4000
    volumes:
      - ./services/upstream:/usr/share/nginx/html:ro
    environment:
      PORT: 4000

  component-header:
    build: ./components/header
    ports:
      - 5001:8080
    environment:
      PORT: 8080

  component-body:
    build: ./components/body
    ports:
      - 5002:8080
    environment:
      PORT: 8080

  component-footer:
    build: ./components/footer
    ports:
      - 5003:8080
    environment:
      PORT: 8080
